-- Kalabhavans.com — initial schema
-- Generated by hand from prisma/schema.prisma (Prisma's own binary-based
-- migration tool wasn't reachable from this environment, so this SQL was
-- written to match exactly what `prisma migrate`/`prisma db push` would
-- produce for this schema). Run this once in the Supabase SQL Editor.

-- Enums
CREATE TYPE "Role" AS ENUM ('member', 'admin');
CREATE TYPE "AgeGroup" AS ENUM ('under_18', 'age_18_24', 'age_25_34', 'age_35_44', 'age_45_54', 'age_55_64', 'age_65_plus');
CREATE TYPE "Gender" AS ENUM ('female', 'male', 'non_binary', 'prefer_not_to_say');
CREATE TYPE "Difficulty" AS ENUM ('easy', 'medium', 'hard');
CREATE TYPE "Continent" AS ENUM ('africa', 'asia', 'europe', 'north_america', 'south_america', 'oceania');
CREATE TYPE "Diet" AS ENUM ('vegetarian', 'vegan', 'non_vegetarian', 'eggetarian');
CREATE TYPE "ReportStatus" AS ENUM ('open', 'dismissed', 'actioned');

-- users
CREATE TABLE "users" (
  "id" TEXT NOT NULL,
  "authUserId" TEXT NOT NULL,
  "firstName" TEXT NOT NULL,
  "lastName" TEXT NOT NULL,
  "email" TEXT NOT NULL,
  "phone" TEXT,
  "gender" "Gender",
  "ageGroup" "AgeGroup",
  "address" TEXT,
  "role" "Role" NOT NULL DEFAULT 'member',
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "users_authUserId_key" ON "users"("authUserId");
CREATE UNIQUE INDEX "users_email_key" ON "users"("email");

-- recipes
CREATE TABLE "recipes" (
  "id" TEXT NOT NULL,
  "slug" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "description" TEXT,
  "continent" "Continent" NOT NULL,
  "country" TEXT NOT NULL,
  "region" TEXT,
  "diet" "Diet" NOT NULL,
  "isStreetFood" BOOLEAN NOT NULL DEFAULT false,
  "cookTimeMin" INTEGER,
  "prepTimeMin" INTEGER,
  "servings" INTEGER,
  "difficulty" "Difficulty" NOT NULL DEFAULT 'medium',
  "imageUrl" TEXT NOT NULL,
  "videoUrl" TEXT,
  "ownerId" TEXT,
  "ownerLabel" TEXT,
  "avgRating" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "ratingCount" INTEGER NOT NULL DEFAULT 0,
  "originalAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "recipes_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "recipes_slug_key" ON "recipes"("slug");
CREATE INDEX "recipes_continent_idx" ON "recipes"("continent");
CREATE INDEX "recipes_country_idx" ON "recipes"("country");
CREATE INDEX "recipes_region_idx" ON "recipes"("region");
CREATE INDEX "recipes_diet_idx" ON "recipes"("diet");
CREATE INDEX "recipes_isStreetFood_idx" ON "recipes"("isStreetFood");
CREATE INDEX "recipes_avgRating_idx" ON "recipes"("avgRating");
ALTER TABLE "recipes" ADD CONSTRAINT "recipes_ownerId_fkey" FOREIGN KEY ("ownerId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- recipe_ingredients
CREATE TABLE "recipe_ingredients" (
  "id" TEXT NOT NULL,
  "recipeId" TEXT NOT NULL,
  "sortOrder" INTEGER NOT NULL DEFAULT 0,
  "quantity" TEXT,
  "name" TEXT NOT NULL,
  CONSTRAINT "recipe_ingredients_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "recipe_ingredients_recipeId_idx" ON "recipe_ingredients"("recipeId");
ALTER TABLE "recipe_ingredients" ADD CONSTRAINT "recipe_ingredients_recipeId_fkey" FOREIGN KEY ("recipeId") REFERENCES "recipes"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- recipe_steps
CREATE TABLE "recipe_steps" (
  "id" TEXT NOT NULL,
  "recipeId" TEXT NOT NULL,
  "stepNumber" INTEGER NOT NULL,
  "instruction" TEXT NOT NULL,
  CONSTRAINT "recipe_steps_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "recipe_steps_recipeId_idx" ON "recipe_steps"("recipeId");
ALTER TABLE "recipe_steps" ADD CONSTRAINT "recipe_steps_recipeId_fkey" FOREIGN KEY ("recipeId") REFERENCES "recipes"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- tags
CREATE TABLE "tags" (
  "id" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "kind" TEXT NOT NULL,
  CONSTRAINT "tags_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "tags_name_key" ON "tags"("name");

-- recipe_tags
CREATE TABLE "recipe_tags" (
  "recipeId" TEXT NOT NULL,
  "tagId" TEXT NOT NULL,
  CONSTRAINT "recipe_tags_pkey" PRIMARY KEY ("recipeId","tagId")
);
ALTER TABLE "recipe_tags" ADD CONSTRAINT "recipe_tags_recipeId_fkey" FOREIGN KEY ("recipeId") REFERENCES "recipes"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "recipe_tags" ADD CONSTRAINT "recipe_tags_tagId_fkey" FOREIGN KEY ("tagId") REFERENCES "tags"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- ratings
CREATE TABLE "ratings" (
  "id" TEXT NOT NULL,
  "recipeId" TEXT NOT NULL,
  "userId" TEXT NOT NULL,
  "score" INTEGER NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "ratings_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "ratings_recipeId_userId_key" ON "ratings"("recipeId","userId");
ALTER TABLE "ratings" ADD CONSTRAINT "ratings_recipeId_fkey" FOREIGN KEY ("recipeId") REFERENCES "recipes"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ratings" ADD CONSTRAINT "ratings_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- comments
CREATE TABLE "comments" (
  "id" TEXT NOT NULL,
  "recipeId" TEXT NOT NULL,
  "userId" TEXT NOT NULL,
  "body" TEXT NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "comments_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "comments_recipeId_idx" ON "comments"("recipeId");
ALTER TABLE "comments" ADD CONSTRAINT "comments_recipeId_fkey" FOREIGN KEY ("recipeId") REFERENCES "recipes"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "comments" ADD CONSTRAINT "comments_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- favorites
CREATE TABLE "favorites" (
  "userId" TEXT NOT NULL,
  "recipeId" TEXT NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "favorites_pkey" PRIMARY KEY ("userId","recipeId")
);
ALTER TABLE "favorites" ADD CONSTRAINT "favorites_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "favorites" ADD CONSTRAINT "favorites_recipeId_fkey" FOREIGN KEY ("recipeId") REFERENCES "recipes"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- reports
CREATE TABLE "reports" (
  "id" TEXT NOT NULL,
  "reporterId" TEXT NOT NULL,
  "recipeId" TEXT,
  "commentId" TEXT,
  "reason" TEXT NOT NULL,
  "status" "ReportStatus" NOT NULL DEFAULT 'open',
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "reports_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "reports_status_idx" ON "reports"("status");
ALTER TABLE "reports" ADD CONSTRAINT "reports_reporterId_fkey" FOREIGN KEY ("reporterId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "reports" ADD CONSTRAINT "reports_recipeId_fkey" FOREIGN KEY ("recipeId") REFERENCES "recipes"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "reports" ADD CONSTRAINT "reports_commentId_fkey" FOREIGN KEY ("commentId") REFERENCES "comments"("id") ON DELETE CASCADE ON UPDATE CASCADE;
